version: '3.7'
services:

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_PORT: ${PG_PORT}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
    networks:
      - postgres

  app:
    container_name: ${PROJECT_NAME}
    build: .
    env_file: .env
    environment:
      - S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    volumes:
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
    depends_on:
      - postgres
    ports:
        - "${PROJECT_PORT}:8000"


networks:
  postgres:
    driver: bridge

volumes:
  pg-data:
    external: true
