version: '3.7'

networks:
  postgres:
    driver: bridge

services:
  app:
    container_name: ${PROJECT_NAME}
    build: .
    networks:
        postgres:
    env_file: .env
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
    ports:
        - "${PROJECT_PORT}:80"

  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
        postgres:
    env_file: .env
    ports:
      - "${PG_PORT}:5432"
